version: '3'

services:
  intruder-alert:
    image: ghcr.io/verifiedjoseph/intruder-alert:latest
    container_name: intruder-alert
    environment:
      - IA_TIMEZONE=America/Los_Angeles
      - IA_MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - IA_LOG_FOLDER=/app/backend/logs
    volumes:
      - ./fail2ban_logs/fail2ban.log:/app/backend/logs/fail2ban.log:ro
      - ./fail2ban_logs/fail2ban.log.1:/app/backend/logs/fail2ban.log.1:ro
      - ./fail2ban_logs/fail2ban.log.2.gz:/app/backend/logs/fail2ban.log.2.gz:ro
      - ./fail2ban_logs/fail2ban.log.3.gz:/app/backend/logs/fail2ban.log.3.gz:ro
      - ./fail2ban_logs/fail2ban.log.4.gz:/app/backend/logs/fail2ban.log.4.gz:ro
    ports:
      - "0.0.0.0:8080:8080"
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /var/lib/nginx/logs
      - /tmp

  nginx-log-normalizer:
    build:
      context: ./nginx-log-normalizer
      dockerfile: Dockerfile
    volumes:
      - ./nginx_logs:/logs
      - ./normalized_logs:/normalized
    command: python3 /app/normalize_nginx_log.py

  goaccess-report:
    image: allinurl/goaccess:latest
    container_name: goaccess-report
    volumes:
      - ./normalized_logs:/logs:ro
      - ./report:/report
    command: >
      goaccess /logs/access.normalized.log
      --log-format=COMBINED
      --date-format=%d/%b/%Y
      --time-format=%T
      --real-time-html
      --output=/report/index.html

  log-normalizer:
    build:
      context: ./log-normalizer
      dockerfile: Dockerfile
    volumes:
      - ./fail2ban_logs:/logs
      - ./normalized_logs:/normalized
