version: '3'

services:
  intruder-alert:
    image: ghcr.io/verifiedjoseph/intruder-alert:latest
    container_name: intruder-alert
    environment:
      - IA_TIMEZONE=America/Los_Angeles
      - IA_MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
      - IA_LOG_FOLDER=/app/backend/logs
      - IA_SYSTEM_LOG_TIMEZONE=America/Los_Angeles
    volumes:
      - ./fail2ban_logs:/app/backend/data/logs:ro
      - /var/log/fail2ban.log:/app/backend/data/logs/fail2ban.log:ro
    ports:
      - "0.0.0.0:8080:8080"
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /var/lib/nginx/logs
      - /tmp

  nginx-log-normalizer:
    build:
      context: ./nginx-log-normalizer
      dockerfile: Dockerfile
    volumes:
      - /home/ryancox/AiRC-Frontend/data/nginx/logs/proxy-host-1_access.log:/srv/logs/access.log:ro
      - ./normalized_logs:/normalized
    command: python3 /app/normalize_nginx_log.py

  goaccess-report:
    image: allinurl/goaccess:latest
    container_name: goaccess-report
    volumes:
      - /home/ryancox/AiRC-Frontend/data/nginx/logs/proxy-host-1_access.log:/srv/logs/access.log:ro
      - ./report:/report
    command: >
      goaccess /srv/logs/access.log --log-format=COMBINED -o /report/index.html

  log-normalizer:
    build:
      context: ./log-normalizer
      dockerfile: Dockerfile
    volumes:
      - ./fail2ban_logs:/app/backend/data/logs:ro
      - /var/log/fail2ban.log:/app/backend/data/logs/fail2ban.log:ro
      - ./normalized_logs:/normalized
